# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be536192ad0ca94cd76e349d6da0532ba9105fd84d1da3730036eecb43e755e2b698c705a9942dacc4699f4293ca5ffa42e38eb830d0f9b5827450404e2cc4ae

test:
  secret_key_base: 7a168cf66c24b13da7363985a978a00303067677f09274a81be886d2d84d6856be9177b705b21632ea4e437f6115d60b6fb58dcc72cfd2db69a58bb05607b173

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
